const errors = {
    WS_CONNECTION: "WS_CONNECTION",
    STAKE_DROP_DELEGATOR_UPDATE: "STAKE_DROP_DELEGATOR_UPDATE",
    STAKE_DROP_ON_NEW_BLOCK: "STAKE_DROP_ON_NEW_BLOCK",
    UPDATE_ERC_ADDRESS: "UPDATE_ERC_ADDRESS",
    PERIODIC_CHECK: "PERIODIC_CHECK"
}

module.exports = errors